"""Multi-Modal Financial Document RAG Pipeline with Hybrid BM25 & Citation Grounding."""

__version__ = "0.1.0"

from multi_modal_financial.agent.pipeline import FinancialRAGPipeline
from multi_modal_financial.analytics.comparator import PeriodComparator, VarianceResult
from multi_modal_financial.analytics.ratios import FinancialRatioCalculator, RatioSummary
from multi_modal_financial.data.cleaner import FinancialDataCleaner
from multi_modal_financial.data.loader import BatchDocumentLoader
from multi_modal_financial.data.synthetic import SyntheticFilingGenerator
from multi_modal_financial.data.validator import (
    FinancialTableValidator,
    ReconciliationResult,
    StatementReconciler,
    ValidationIssue,
    ValidationReport,
)
from multi_modal_financial.grounding.audit import GroundingAuditor, GroundingAuditReport
from multi_modal_financial.indexing.hybrid import HybridIndex
from multi_modal_financial.interfaces import (
    CrossEncoderProtocol,
    DenseIndexProtocol,
    RerankerProtocol,
    RetrieverProtocol,
    SemanticCacheProtocol,
    SparseIndexProtocol,
)
from multi_modal_financial.pipeline.orchestrator import (
    FinancialPipelineOrchestrator,
    OrchestratorConfig,
)
from multi_modal_financial.retrieval.fusion import HybridRetriever
from multi_modal_financial.retrieval.reranker import FinancialCrossEncoder, FinancialReranker
from multi_modal_financial.storage.cache import EmbeddingCache, QueryCache, SemanticCache
from multi_modal_financial.storage.persistence import IndexManifest, IndexPersistence
from multi_modal_financial.types import (
    AgentQuery,
    AgentResponse,
    BaseFinancialModel,
    CacheEvictionPolicy,
    CacheHitType,
    Chunk,
    Citation,
    Currency,
    Document,
    DocumentMetadata,
    DocumentType,
    ExtractionFilter,
    FigureData,
    FinancialMetric,
    FinancialStatementType,
    GroundingStatus,
    GroundingVerdict,
    HybridSearchConfig,
    ModalType,
    ProvenanceRecord,
    QueryIntent,
    RerankerConfig,
    RerankerStrategy,
    RerankExplanation,
    RetrievalBenchmarkResult,
    RetrievalStrategy,
    ScoredChunk,
    SemanticCacheConfig,
    SemanticCacheEntry,
    SemanticCacheLookupResult,
    SemanticCacheStats,
    TableData,
    UnitScale,
    scale_multiplier,
)

__all__ = [
    "__version__",
    "BaseFinancialModel",
    "ModalType",
    "DocumentType",
    "FinancialStatementType",
    "Currency",
    "UnitScale",
    "scale_multiplier",
    "QueryIntent",
    "GroundingStatus",
    "RerankerStrategy",
    "RetrievalStrategy",
    "CacheEvictionPolicy",
    "CacheHitType",
    "FinancialMetric",
    "DocumentMetadata",
    "TableData",
    "FigureData",
    "Chunk",
    "Document",
    "ScoredChunk",
    "Citation",
    "GroundingVerdict",
    "AgentQuery",
    "AgentResponse",
    "RerankExplanation",
    "RerankerConfig",
    "HybridSearchConfig",
    "SemanticCacheConfig",
    "SemanticCacheEntry",
    "SemanticCacheLookupResult",
    "SemanticCacheStats",
    "CrossEncoderProtocol",
    "RerankerProtocol",
    "SemanticCacheProtocol",
    "DenseIndexProtocol",
    "SparseIndexProtocol",
    "RetrieverProtocol",
    "RetrievalBenchmarkResult",
    "ProvenanceRecord",
    "ExtractionFilter",
    "HybridIndex",
    "HybridRetriever",
    "FinancialCrossEncoder",
    "FinancialReranker",
    "FinancialRAGPipeline",
    "FinancialDataCleaner",
    "FinancialTableValidator",
    "StatementReconciler",
    "ValidationIssue",
    "ValidationReport",
    "ReconciliationResult",
    "SyntheticFilingGenerator",
    "BatchDocumentLoader",
    "IndexPersistence",
    "IndexManifest",
    "EmbeddingCache",
    "QueryCache",
    "SemanticCache",
    "FinancialRatioCalculator",
    "RatioSummary",
    "PeriodComparator",
    "VarianceResult",
    "GroundingAuditor",
    "GroundingAuditReport",
    "FinancialPipelineOrchestrator",
    "OrchestratorConfig",
]
